#https://github.com/codecov/example-android/blob/master/.travis.yml
#https://guides.codepath.com/android/Setting-up-Travis-CI
#https://unicorn-utterances.com/posts/travis-ci-for-android/
env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$HOME/swig/bin:$PATH

language: android

jdk:
  - oraclejdk8

git:
  submodules: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    # lookup below for default buildToolsVersion in accordance to AGP version
    # https://developer.android.com/studio/releases/gradle-plugin.html#3-4-0
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28
    - android-22

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-17
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# ripped from https://github.com/googlesamples/android-ndk/blob/ae0bb4de/.travis.yml
addons:
  apt:
    packages:
      - automake
      - bison
      - python3-pip
#    - pandoc

# clone dawg-java & dawg-java/swig
before_install:
  - git submodule update --init --recursive --depth=1
  - pip3 install awscli --upgrade --user

install:
  # build_swig will skip if swig is found.
  - export PATH=$HOME/swig/bin:$PATH
  - cd dawg-java
  - ./build_swig.sh $HOME/swig
  - cd ..

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &

script:
  - |
    fold_start() {
      echo -e "travis_fold:start:$1\033[33;1m$2\033[0m"
    }
    fold_end() {
      echo -e "\ntravis_fold:end:$1\r"
    }
  # from https://github.com/travis-ci/travis-rubies/blob/9f7962a881c55d32da7c76baefc58b89e3941d91/build.sh#L38-L44
  - fold_start lib.build "gradle :lib:build"
  - ./gradlew -Plint.output.console=true --info :lib:build
  - fold_end lib.build
  - fold_start app.build "gradle :app:build"
  - ./gradlew -Plint.output.console=true --info :app:build
  - fold_end app.build
  - fold_start app.cAT "gradle :app:connectedAndroidTest"
  - |
    android-wait-for-emulator
    adb shell settings put global window_animation_scale 0 &
    adb shell settings put global transition_animation_scale 0 &
    adb shell settings put global animator_duration_scale 0 &
    adb shell input keyevent KEYCODE_MENU &
  - ./gradlew -Plint.output.console=true --info connectedAndroidTest
  - fold_end app.cAT

after_failure:
  - export s3key="lib-test/$(git rev-parse --short HEAD)"
  - "aws s3 cp --recursive lib/build/reports/tests/test/ s3://t9vietnamese/$s3key/
      --acl public-read --expires $(date -Iseconds -d '3 months')"
  - "echo View test result at: https://t9vietnamese.s3-ap-northeast-1.amazonaws.com/$s3key/index.html"

# cache between builds
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/swig

deploy:
  - provider: bintray
    skip_cleanup: true
    file: "bintray-descriptor.json"
    user: "kentvu"
    key:
      secure: "hpZPPt/ygLw6fLlkLq64/xQNWf23Z7QDcS+xKvDQ6qX+ULUyrpav4v37KLTRHgtwOcG3HOScOQwkAa06HRBsSlCnTfNKpxS9Vs4rZPdyZaxYanumXHdLc47wvNC2EpzN22S4Juv4rKAtONHgFbZzggmTC9oC3Cb3OAA/+sgF3IdhC7uO+cfCw7PBaD8ZUYupu/8uorOyZcDAFhxyyBxoGGKUAbqcgKVhSMS+XmoVhPAc6wAlRQWWzz09nUK4eAG2m7g+3V192zy6BZb4J1JIIAeiEL5UnmF72u4Ar7fm+E2Uc7kxFnUFISNYbKn5tkruiUgPCzOXPScLhB7T/O0r108VHq9zppJWT/5Husv3udRgoPoY54JFNZmmC2VDbnQiH+GUxYW64jS16vqDAFsicEMdugNd8pc+pPRyv3ZaXT0JhsS+LjhstJlyEb7im4dxwRrYkzh7AHJFtiq4wHwlKcZADpe9LUvpgFXLoDBAOFVnKg0C8UL13tjNiqJJN9zSlRsEd54HHzykr1TwC5l70GlTSSjzToPqDlpCdx+mtiVFyVLmTKPerGZqspVcyZ6i5PlHCEubgc00uVb1BnglfFeZZoUfNdM7WLby78F5HPTTlJTpllNuGDVXBggSot0jwXrCEH0vkrTMbGOBiiMnMxJ2SuJ+trWC6gG0DZe/SIs="

#  passphrase: "Optional. In case a passphrase is configured on Bintray and GPG signing is used"
#  dry-run: "Optional. If true, skips sending requests to Bintray. Useful for testing your configuration"
