[versions]

project = "1.0.0"
kotlin = "2.2.10" # https://github.com/JetBrains/kotlin/releases
agp = "8.11.1" # https://developer.android.com/studio/releases/gradle-plugin
jvmTarget = "11"
#jvmToolchain = "17"

android-minSdk = "24"
android-compileSdk = "36"
android-targetSdk = "34"

compose-multiplatform = "1.7.3" # https://github.com/JetBrains/compose-multiplatform/releases
compose-ui = "1.7.8" # https://developer.android.com/jetpack/androidx/releases/compose-ui
#uiTestAndroid = "1.8.2"

coroutines = "1.10.1" # https://github.com/Kotlin/kotlinx.coroutines
coroutines-test = "1.10.1" # https://github.com/Kotlin/kotlinx.coroutines

androidx-activity = "1.9.0"
androidx-activityCompose = "1.10.1" # https://developer.android.com/jetpack/androidx/releases/activity # androidx-activity-compose
androidx-appcompat = "1.6.1"
androidx-core = "1.15.0" # https://developer.android.com/jetpack/androidx/releases/core
androidx-core-ktx = "1.15.0" # https://developer.android.com/jetpack/androidx/releases/core

junit = "4.13.2"
decompose = "3.1.0"
essenty = "2.1.0"
koin = "4.0.2" # https://github.com/InsertKoinIO/koin#setup--current-version
sqlDelight = "2.0.2" # https://github.com/cashapp/sqldelight/releases
datetime = "0.6.2" # https://github.com/Kotlin/kotlinx-datetime
kotlinxSerialization = "1.6.3"

ksp = "2.2.10-2.0.2"
kotest = "6.0.0"

[plugins]

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotest = { id = "io.kotest", version.ref = "kotest" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]

androidx-activity-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidx-core" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-ui" }
androidx-compose-ui-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-ui" }
androidx-ui-test-android = { group = "androidx.compose.ui", name = "ui-test-android", version.ref = "compose-ui" }

kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-test" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
napier = { group = "io.github.aakira", name = "napier", version = "2.6.1" }
okio = { group = "com.squareup.okio", name = "okio", version = "3.8.0" }
okio-fakefilesystem = { group = "com.squareup.okio", name = "okio-fakefilesystem", version = "3.8.0" }
doistx-normalize = { group = "com.doist.x", name = "normalize", version = "1.0.5" }

kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
