# https://github.com/DeployGate/deploygate-upload-github-action
name: Deploy Android App to DeployGate

on:
  #pull_request:
  #  branches:
  #    - main
  #  types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      # Enable these for signing with custom key.
      DEBUG_KEYSTORE: "${{ github.workspace }}/debug.keystore"
      DEBUG_KEYSTORE_PASSWORD: android
      DEBUG_KEY_ALIAS: androiddebugkey
      DEBUG_KEY_PASSWORD: android

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # https://github.com/Julow/Unexpected-Keyboard/blob/master/.github/workflows/make-apk.yml
      - name: Restore debug keystore from GitHub Secrets
        run: |
          # Check if exist and use the secret named DEBUG_KEYSTORE
          # The contents of the secret can be obtained -
          #  from the debug.keystore.asc from you local folder 
          #  (refer to CONTRIBUTING.md Using the local debug.keystore on the Github CI actions)
          if [[ ! "${{ secrets.DEBUG_KEYSTORE }}" = "" ]]; then
              echo "${{ secrets.DEBUG_KEYSTORE }}" > "debug.keystore.asc"
              if [[ -s "debug.keystore.asc" ]]; then
                  echo "Restoring debug keystore from GitHub secrets"
                  mkdir -pv ~/.android
                  gpg -d --passphrase "debug0" --batch "debug.keystore.asc" > ~/.android/debug.keystore
                  cp -lv ~/.android/debug.keystore $DEBUG_KEYSTORE
              fi
          fi

      - name: UI Test
        run: ./gradlew :common:jvmTest :common:ui:jvmTest

      - name: Persist test result
        uses: actions/upload-artifact@v4
        with:
          name: vietnamese-t9-ime-test-result
          path: | #webDemo/build/test-results/
            common/build/test-results/
            common/build/reports/tests/jvmTest/
            common/ui/build/test-results/
            common/ui/build/reports/tests/jvmTest/

      - name: Build Debug Bundle
        run: ./gradlew :app:bundleDebug

      - name: Upload AAB to DeployGate
        id: deploygate
        uses: DeployGate/deploygate-upload-github-action@v1.1.0
        with:
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          owner_name: ${{ secrets.DEPLOYGATE_OWNER_NAME }}
          file_path: app/build/outputs/bundle/debug/app-debug.aab
          #message: "PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"
          message: "T9Vietnamese release."
          #distribution_name: "PR #${github.event.pull_request.number}"
          release_note: |
            Branch: ${{ github.head_ref }}
            Commit: ${{ github.sha }}

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug APK
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: t9-ime-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
