name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEPLOYGATE_APP_OWNER_NAME: KentVu
      DEPLOYGATE_API_TOKEN: ${{ secrets.DEPLOYGATE_API_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache build
        id: cache-build
        uses: actions/cache@v1
        with:
          path: |
            ~/.m2
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android
          key: ${{ runner.os }}-build-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8'

      - name: Build with Gradle & SWIG
        run: |
          ./gradlew clean
          ./gradlew -Plint.output.console=true :lib:build
          ./gradlew -Plint.output.console=true :app:build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: |
            lib/build/test-results/**/*.xml
            app/build/test-results/**/*.xml

      - name: Upload DeployGate
        run: |
          ./gradlew :app:uploadDeployGateDebug

  android-test:
    runs-on: macOS-latest # macos-11.0 is not public for now
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache build
        id: cache-build
        uses: actions/cache@v1
        with:
          path: |
            ~/.m2
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android
          key: ${{ runner.os }}-build-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160
          script: |
            adb logcat -c
            adb logcat *:E -v color &
            ./gradlew -Plint.output.console=true --info connectedCheck

      - name: Persist test result
        uses: actions/upload-artifact@v1.0.0
        with:
          name: vietnamese-t9-ime-test-result
          path: app/build/outputs/androidTest-results/connected

      - name: Upload apk
        continue-on-error: true
        uses: actions/upload-artifact@v1.0.0
        with:
          name: vietnamese-t9-ime-apk
          path: app/build/outputs/apk

      - name: Upload dylibs
        continue-on-error: true
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dawg-jni-darwin
          path: dawg-java/dawg-java/src/main/resources
