# https://github.com/DeployGate/deploygate-upload-github-action
name: Deploy Android App to DeployGate

on:
  #pull_request:
  #  branches:
  #    - main
  #  types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: UI Test
        run: ./gradlew :common:jvmTest :common:ui:jvmTest

      - name: Build Release Bundle
        run: ./gradlew :app:bundleDebug

      - name: Upload AAB to DeployGate
        id: deploygate
        uses: DeployGate/deploygate-upload-github-action@v1.1.0
        with:
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          owner_name: ${{ secrets.DEPLOYGATE_OWNER_NAME }}
          file_path: app/build/outputs/bundle/debug/app-debug.aab
          #message: "PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"
          message: "T9Vietnamese release."
          #distribution_name: "PR #${github.event.pull_request.number}"
          release_note: |
            Branch: ${{ github.head_ref }}
            Commit: ${{ github.sha }}

