# https://github.com/DeployGate/deploygate-upload-github-action
name: Deploy Android App to DeployGate

on:
  #pull_request:
  #  branches:
  #    - main
  #  types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # https://github.com/Julow/Unexpected-Keyboard/blob/master/.github/workflows/make-apk.yml
      - name: Restore debug keystore from GitHub Secrets
        run: |
          # Check if exist and use the secret named DEBUG_KEYSTORE
          # The contents of the secret can be obtained -
          #  from the debug.keystore.asc from you local folder 
          #  (refer to CONTRIBUTING.md Using the local debug.keystore on the Github CI actions)
          if [[ ! "${{ secrets.DEBUG_KEYSTORE }}" = "" ]]; then
              echo "${{ secrets.DEBUG_KEYSTORE }}" > "debug.keystore.asc"
              if [[ -s "debug.keystore.asc" ]]; then
                  echo "Restoring debug keystore from GitHub secrets"
                  mkdir -pv ~/.android
                  gpg -d --passphrase "debug0" --batch "debug.keystore.asc" > ~/.android/debug.keystore
              fi
          fi

      - name: UI Test
        run: ./gradlew :common:jvmTest :common:ui:jvmTest

      - name: Build Release Bundle
        run: ./gradlew :app:bundleDebug

      - name: Upload AAB to DeployGate
        id: deploygate
        uses: DeployGate/deploygate-upload-github-action@v1.1.0
        with:
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          owner_name: ${{ secrets.DEPLOYGATE_OWNER_NAME }}
          file_path: app/build/outputs/bundle/debug/app-debug.aab
          #message: "PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"
          message: "T9Vietnamese release."
          #distribution_name: "PR #${github.event.pull_request.number}"
          release_note: |
            Branch: ${{ github.head_ref }}
            Commit: ${{ github.sha }}

